[tool.poetry]
name = "porlygon"
version = "0.1.0"
description = ""
authors = ["infcode <infcode@163.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
